### ISSUE TITLE
Takes a while to load

### ISSUE THREAD

**Issue by ChloeWolfieGirl** [uMatriks/uMatriks#14]
When you open the app you are welcomed to a "Please Wait..." for about 12 seconds, if possible this should be sped up so people can see the groups immediately, or at least asap.

**Comment by mariogrip** [comment]
You need to be more patient @ChloeWolfieGirl, life is not quick :fast_forward:

**Comment by ChloeWolfieGirl** [comment]
@mariogrip 
![gotta-go-fast](https://user-images.githubusercontent.com/8162805/28984638-e9a47f66-7956-11e7-978e-784f141f2882.gif)

**Comment by LarreaMikel** [comment]
The loading time is also considerable in apps like riot, so maybe this is something intrinsic to matrix. Nevertheless this bug should remain open until we investigate this matter.

**Comment by delijati** [comment]
It should load faster caching is activated now
