### ISSUE TITLE
[Feature Request] Possible port to Sailfish OS

### ISSUE THREAD

**Issue by rodneyrod** [uMatriks/uMatriks#39]
Since both platforms use Qt and QML base libraries, such a port might be possible with little extra work.

**Comment by delijati** [comment]
Currently the widgets are ubuntu specific and not just a theme so reusing them wont be possible. It also depens on some ubuntu specific tools aka `content-hub`

**Comment by KitsuneRal** [comment]
See the latest updates in davidar/tensor#4. As for uMatriks, I believe the project has already gone too far into Ubuntu-specific land so porting it to SailfishOS would by definition be harder than porting https://github.com/Quiark/tensor.
