### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by Nativeworld** [uMatriks/uMatriks#61]
Since the last uMatriks-update (UT 15.04 and uMatrix 0.9) it is not possible to login with tchncs.de account. 
To try login going endless. Other users have the same problem.

**Comment by delijati** [comment]
Can you provide `logs`.

**Comment by LarreaMikel** [comment]
I have a successful login with the tchncs.de account. Have you tried re-writing all the account settings (even when they are already there) ?

**Comment by Nativeworld** [comment]
Am Montag, 26. Februar 2018, 12:14:51 CET schrieb LarreaMikel:
> I have a successful login with the tchncs.de account. Have you tried
> re-writing all the account settings (even when they are already there) ?

Okay. Thank you for your suggestion. When i open the app, the username is 
already visible, therefore i don't think that i must the username  once more 
fill in.
This was my mistake. 
I'm so sorry for it. 

Best greetings to you
