### ISSUE TITLE
Needs to be recompiled for 16.04

### ISSUE THREAD

**Issue by PhoenixLandPirate** [uMatriks/uMatriks#64]
uMatriks doesn't work on 16.04, so would need to be recompiled for the 16.04 version of the Ubuntu Touch operating system.

**Comment by PhoenixLandPirate** [comment]
Clickable bug is now closed.
Flo in the latest Q&A recommends it.
https://youtu.be/PEgIKstkTQE?t=20m39s

**Comment by LarreaMikel** [comment]
There is already a 16.04 version. I Will close this issue, and if there is any problem we could re-open it.

**Comment by PhoenixLandPirate** [comment]
Where can you get the 16.04 version from?

**Comment by cibersheep** [comment]
@PhoenixLandPirate you can check: https://open-store.io/app/umatriks.larreamikel
There's a download for Xenial

**Comment by LarreaMikel** [comment]
Yes, that's an annoying bug that uMatriks has.
As @cibersheep said, you can download the app for xenial from the store.
